[package]
name    = "legit"
description = "add proof of work to a git commit"
version = "0.1.0"
authors = ["@RandyMcMillan <randy.lee.mcmillan@gmail.com>", "John <john@throttle.io>"]
edition = "2021"
readme = "README.md"
documentation = "https://legit.randymcmillan.net"
homepage = "https://legit.randymcmillan.net/"
repository = "https://github.com/randymcmillan/legit.git"
license = "MIT OR Apache-2.0"



[dependencies]
rust-crypto = "*"
git2        = "*"
argparse    = "*"
time        = "*"

