[package]
name    = "legit"
description = "add proof of work to a git commit"
version = "0.1.0"
authors = ["@RandyMcMillan <randy.lee.mcmillan@gmail.com>", "John <john@throttle.io>"]
edition = "2021"

[dependencies]
rust-crypto = "*"
git2        = "*"
argparse    = "*"
time        = "*"

