name: macos-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  macos-build_and_test:
    strategy:
      matrix:
        os: [macos-latest, macos-11, macos-12]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: printenv
        run: |
          brew install libtool autoconf automake 
          printenv
      - name: make
        run: |
          make
      - name: sudo make legit
        run: |
          sudo make legit
      - name: cargo build --release
        run: |
          cargo build --release

      - name: cargo run 
        run: |
          cargo run
          cargo run . -p b -m ""
          #pipe handles non-zero return from nostril default help
          sudo -su runner nostril        | echo "${PIPESTATUS[0]}"
