name: ubuntu-matrix

# Controls when the action will run.
on:
  pull_request:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - 'master'
      - 'main'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-build_and_test:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: printenv
        run: |
          #brew install libtool autoconf automake
          printenv
      - name: make
        run: |
          sudo apt-get install libssl-dev
          make
      - name: sudo make legit
        run: |
          sudo -su runner make legit
      - name: cargo build --release
        run: |
          sudo -su runner cargo build --release

      - name: cargo run
        run: |
          sudo -su runner cargo run | echo "${PIPESTATUS[0]}"
